// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
)

type Evaluation struct {
	ID         int64
	OfferKey   string
	ProfileID  int64
	Grade      string
	Dimensions string
	Rationale  string
	CreatedAt  string
}

type Offer struct {
	OfferKey        string
	Title           string
	Company         string
	Division        string
	Category        sql.NullString
	SubCategory     sql.NullString
	ExperienceLevel sql.NullString
	SalaryFrom      sql.NullInt64
	SalaryTo        sql.NullInt64
	Currency        sql.NullString
	IsRemote        int64
	IsHybrid        int64
	ValidFrom       sql.NullString
	ValidTo         sql.NullString
	Url             sql.NullString
	Locations       sql.NullString
	Skills          sql.NullString
	Raw             string
	FetchedAt       string
}

type Profile struct {
	ID        int64
	Name      string
	Content   string
	IsDefault int64
	CreatedAt string
	UpdatedAt string
}

type Seen struct {
	OfferKey string
	SeenAt   string
}

type Tracker struct {
	OfferKey  string
	ProfileID int64
	Status    string
	Notes     string
	CreatedAt string
	UpdatedAt string
}

type Watch struct {
	ID        int64
	Name      string
	Division  string
	Params    string
	CreatedAt string
}
