// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"strings"
)

const countProfiles = `-- name: CountProfiles :one
SELECT COUNT(*) FROM profiles
`

func (q *Queries) CountProfiles(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProfiles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const defaultProfile = `-- name: DefaultProfile :one
SELECT id, name, content, is_default, created_at, updated_at
FROM profiles WHERE is_default = 1 LIMIT 1
`

func (q *Queries) DefaultProfile(ctx context.Context) (Profile, error) {
	row := q.db.QueryRowContext(ctx, defaultProfile)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Content,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireStale = `-- name: ExpireStale :execrows
UPDATE tracker SET status = 'expired', updated_at = ?1
WHERE profile_id = ?2
  AND status NOT IN ('expired', 'offer', 'rejected')
  AND offer_key IN (
      SELECT offer_key FROM offers
      WHERE valid_to != '' AND valid_to < ?3)
`

type ExpireStaleParams struct {
	UpdatedAt string
	ProfileID int64
	Cutoff    sql.NullString
}

func (q *Queries) ExpireStale(ctx context.Context, arg ExpireStaleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, expireStale, arg.UpdatedAt, arg.ProfileID, arg.Cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getInterviewPrep = `-- name: GetInterviewPrep :one
SELECT id, offer_key, profile_id, readiness, gaps, questions_to_ask, summary, created_at, updated_at
FROM interview_preps
WHERE id = ?
`

func (q *Queries) GetInterviewPrep(ctx context.Context, id int64) (InterviewPrep, error) {
	row := q.db.QueryRowContext(ctx, getInterviewPrep, id)
	var i InterviewPrep
	err := row.Scan(
		&i.ID,
		&i.OfferKey,
		&i.ProfileID,
		&i.Readiness,
		&i.Gaps,
		&i.QuestionsToAsk,
		&i.Summary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOfferRaw = `-- name: GetOfferRaw :one
SELECT raw FROM offers WHERE offer_key = ?
`

func (q *Queries) GetOfferRaw(ctx context.Context, offerKey string) (string, error) {
	row := q.db.QueryRowContext(ctx, getOfferRaw, offerKey)
	var raw string
	err := row.Scan(&raw)
	return raw, err
}

const getProfile = `-- name: GetProfile :one
SELECT id, name, content, is_default, created_at, updated_at
FROM profiles WHERE id = ?
`

func (q *Queries) GetProfile(ctx context.Context, id int64) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getProfile, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Content,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileByName = `-- name: GetProfileByName :one
SELECT id, name, content, is_default, created_at, updated_at
FROM profiles WHERE name = ?
`

func (q *Queries) GetProfileByName(ctx context.Context, name string) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getProfileByName, name)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Content,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQuestion = `-- name: GetQuestion :one
SELECT id, prep_id, category, question, difficulty, talking_points, confidence, practiced_count, created_at, updated_at
FROM interview_questions
WHERE id = ?
`

func (q *Queries) GetQuestion(ctx context.Context, id int64) (InterviewQuestion, error) {
	row := q.db.QueryRowContext(ctx, getQuestion, id)
	var i InterviewQuestion
	err := row.Scan(
		&i.ID,
		&i.PrepID,
		&i.Category,
		&i.Question,
		&i.Difficulty,
		&i.TalkingPoints,
		&i.Confidence,
		&i.PracticedCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTracked = `-- name: GetTracked :one
SELECT t.offer_key, t.profile_id, t.status, t.notes,
       o.title, o.company, o.url, o.valid_to,
       t.created_at, t.updated_at
FROM tracker t
JOIN offers o ON o.offer_key = t.offer_key
WHERE t.offer_key = ? AND t.profile_id = ?
`

type GetTrackedParams struct {
	OfferKey  string
	ProfileID int64
}

type GetTrackedRow struct {
	OfferKey  string
	ProfileID int64
	Status    string
	Notes     string
	Title     string
	Company   string
	Url       sql.NullString
	ValidTo   sql.NullString
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) GetTracked(ctx context.Context, arg GetTrackedParams) (GetTrackedRow, error) {
	row := q.db.QueryRowContext(ctx, getTracked, arg.OfferKey, arg.ProfileID)
	var i GetTrackedRow
	err := row.Scan(
		&i.OfferKey,
		&i.ProfileID,
		&i.Status,
		&i.Notes,
		&i.Title,
		&i.Company,
		&i.Url,
		&i.ValidTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWatchByName = `-- name: GetWatchByName :one
SELECT id, name, division, params, created_at FROM watches WHERE name = ?
`

func (q *Queries) GetWatchByName(ctx context.Context, name string) (Watch, error) {
	row := q.db.QueryRowContext(ctx, getWatchByName, name)
	var i Watch
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Division,
		&i.Params,
		&i.CreatedAt,
	)
	return i, err
}

const insertEvaluation = `-- name: InsertEvaluation :one

INSERT INTO evaluations (offer_key, profile_id, grade, dimensions, rationale, created_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, created_at
`

type InsertEvaluationParams struct {
	OfferKey   string
	ProfileID  int64
	Grade      string
	Dimensions string
	Rationale  string
	CreatedAt  string
}

type InsertEvaluationRow struct {
	ID        int64
	CreatedAt string
}

// ===== evaluations =====
func (q *Queries) InsertEvaluation(ctx context.Context, arg InsertEvaluationParams) (InsertEvaluationRow, error) {
	row := q.db.QueryRowContext(ctx, insertEvaluation,
		arg.OfferKey,
		arg.ProfileID,
		arg.Grade,
		arg.Dimensions,
		arg.Rationale,
		arg.CreatedAt,
	)
	var i InsertEvaluationRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const insertInterviewPrep = `-- name: InsertInterviewPrep :one

INSERT INTO interview_preps (offer_key, profile_id, readiness, gaps, questions_to_ask, summary, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, created_at, updated_at
`

type InsertInterviewPrepParams struct {
	OfferKey       string
	ProfileID      int64
	Readiness      int64
	Gaps           string
	QuestionsToAsk string
	Summary        string
	CreatedAt      string
	UpdatedAt      string
}

type InsertInterviewPrepRow struct {
	ID        int64
	CreatedAt string
	UpdatedAt string
}

// ===== interviews =====
func (q *Queries) InsertInterviewPrep(ctx context.Context, arg InsertInterviewPrepParams) (InsertInterviewPrepRow, error) {
	row := q.db.QueryRowContext(ctx, insertInterviewPrep,
		arg.OfferKey,
		arg.ProfileID,
		arg.Readiness,
		arg.Gaps,
		arg.QuestionsToAsk,
		arg.Summary,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i InsertInterviewPrepRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const insertInterviewQuestion = `-- name: InsertInterviewQuestion :one
INSERT INTO interview_questions (prep_id, category, question, difficulty, talking_points, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertInterviewQuestionParams struct {
	PrepID        int64
	Category      string
	Question      string
	Difficulty    string
	TalkingPoints string
	CreatedAt     string
	UpdatedAt     string
}

func (q *Queries) InsertInterviewQuestion(ctx context.Context, arg InsertInterviewQuestionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertInterviewQuestion,
		arg.PrepID,
		arg.Category,
		arg.Question,
		arg.Difficulty,
		arg.TalkingPoints,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertProfile = `-- name: InsertProfile :one

INSERT INTO profiles (name, content, is_default, created_at, updated_at)
VALUES (?, ?, 0, ?, ?)
RETURNING id
`

type InsertProfileParams struct {
	Name      string
	Content   string
	CreatedAt string
	UpdatedAt string
}

// ===== profiles =====
func (q *Queries) InsertProfile(ctx context.Context, arg InsertProfileParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertProfile,
		arg.Name,
		arg.Content,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertTracked = `-- name: InsertTracked :exec

INSERT INTO tracker (offer_key, profile_id, status, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(offer_key, profile_id) DO NOTHING
`

type InsertTrackedParams struct {
	OfferKey  string
	ProfileID int64
	Status    string
	CreatedAt string
	UpdatedAt string
}

// ===== tracker =====
func (q *Queries) InsertTracked(ctx context.Context, arg InsertTrackedParams) error {
	_, err := q.db.ExecContext(ctx, insertTracked,
		arg.OfferKey,
		arg.ProfileID,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const isSeen = `-- name: IsSeen :one
SELECT EXISTS(SELECT 1 FROM seen WHERE offer_key = ?)
`

func (q *Queries) IsSeen(ctx context.Context, offerKey string) (bool, error) {
	row := q.db.QueryRowContext(ctx, isSeen, offerKey)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const latestEvaluation = `-- name: LatestEvaluation :one
SELECT id, offer_key, profile_id, grade, dimensions, rationale, created_at
FROM evaluations
WHERE offer_key = ? AND profile_id = ?
ORDER BY created_at DESC, id DESC LIMIT 1
`

type LatestEvaluationParams struct {
	OfferKey  string
	ProfileID int64
}

func (q *Queries) LatestEvaluation(ctx context.Context, arg LatestEvaluationParams) (Evaluation, error) {
	row := q.db.QueryRowContext(ctx, latestEvaluation, arg.OfferKey, arg.ProfileID)
	var i Evaluation
	err := row.Scan(
		&i.ID,
		&i.OfferKey,
		&i.ProfileID,
		&i.Grade,
		&i.Dimensions,
		&i.Rationale,
		&i.CreatedAt,
	)
	return i, err
}

const latestInterviewPrep = `-- name: LatestInterviewPrep :one
SELECT id, offer_key, profile_id, readiness, gaps, questions_to_ask, summary, created_at, updated_at
FROM interview_preps
WHERE offer_key = ? AND profile_id = ?
ORDER BY created_at DESC, id DESC LIMIT 1
`

type LatestInterviewPrepParams struct {
	OfferKey  string
	ProfileID int64
}

func (q *Queries) LatestInterviewPrep(ctx context.Context, arg LatestInterviewPrepParams) (InterviewPrep, error) {
	row := q.db.QueryRowContext(ctx, latestInterviewPrep, arg.OfferKey, arg.ProfileID)
	var i InterviewPrep
	err := row.Scan(
		&i.ID,
		&i.OfferKey,
		&i.ProfileID,
		&i.Readiness,
		&i.Gaps,
		&i.QuestionsToAsk,
		&i.Summary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInterviewPreps = `-- name: ListInterviewPreps :many
SELECT p.id, p.offer_key, p.profile_id, p.readiness, p.summary,
       p.created_at, p.updated_at,
       o.title, o.company, o.url
FROM interview_preps p
JOIN offers o ON o.offer_key = p.offer_key
WHERE p.profile_id = ?
  AND p.id = (
      SELECT p2.id FROM interview_preps p2
      WHERE p2.offer_key = p.offer_key AND p2.profile_id = p.profile_id
      ORDER BY p2.created_at DESC, p2.id DESC LIMIT 1)
ORDER BY p.updated_at DESC, p.id DESC
`

type ListInterviewPrepsRow struct {
	ID        int64
	OfferKey  string
	ProfileID int64
	Readiness int64
	Summary   string
	CreatedAt string
	UpdatedAt string
	Title     string
	Company   string
	Url       sql.NullString
}

// Latest prep per offer for a profile (history is preserved, but the list shows
// one row per offer), decorated with the offer's title/company/url.
func (q *Queries) ListInterviewPreps(ctx context.Context, profileID int64) ([]ListInterviewPrepsRow, error) {
	rows, err := q.db.QueryContext(ctx, listInterviewPreps, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInterviewPrepsRow{}
	for rows.Next() {
		var i ListInterviewPrepsRow
		if err := rows.Scan(
			&i.ID,
			&i.OfferKey,
			&i.ProfileID,
			&i.Readiness,
			&i.Summary,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Company,
			&i.Url,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfiles = `-- name: ListProfiles :many
SELECT id, name, content, is_default, created_at, updated_at
FROM profiles ORDER BY is_default DESC, name ASC
`

func (q *Queries) ListProfiles(ctx context.Context) ([]Profile, error) {
	rows, err := q.db.QueryContext(ctx, listProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Profile{}
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Content,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTracked = `-- name: ListTracked :many
SELECT t.offer_key, t.profile_id, t.status, t.notes,
       o.title, o.company, o.url, o.valid_to,
       COALESCE((SELECT e.grade FROM evaluations e
                 WHERE e.offer_key = t.offer_key AND e.profile_id = t.profile_id
                 ORDER BY e.created_at DESC LIMIT 1), '') AS grade,
       t.created_at, t.updated_at
FROM tracker t
JOIN offers o ON o.offer_key = t.offer_key
WHERE t.profile_id = ?1
  AND (CAST(?2 AS TEXT) IS NULL OR t.status = ?2)
ORDER BY t.updated_at DESC
`

type ListTrackedParams struct {
	ProfileID int64
	Status    sql.NullString
}

type ListTrackedRow struct {
	OfferKey  string
	ProfileID int64
	Status    string
	Notes     string
	Title     string
	Company   string
	Url       sql.NullString
	ValidTo   sql.NullString
	Grade     interface{}
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) ListTracked(ctx context.Context, arg ListTrackedParams) ([]ListTrackedRow, error) {
	rows, err := q.db.QueryContext(ctx, listTracked, arg.ProfileID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTrackedRow{}
	for rows.Next() {
		var i ListTrackedRow
		if err := rows.Scan(
			&i.OfferKey,
			&i.ProfileID,
			&i.Status,
			&i.Notes,
			&i.Title,
			&i.Company,
			&i.Url,
			&i.ValidTo,
			&i.Grade,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWatches = `-- name: ListWatches :many
SELECT id, name, division, params, created_at FROM watches ORDER BY name ASC
`

func (q *Queries) ListWatches(ctx context.Context) ([]Watch, error) {
	rows, err := q.db.QueryContext(ctx, listWatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Watch{}
	for rows.Next() {
		var i Watch
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Division,
			&i.Params,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSeen = `-- name: MarkSeen :execrows

INSERT INTO seen (offer_key, seen_at) VALUES (?, ?)
ON CONFLICT(offer_key) DO NOTHING
`

type MarkSeenParams struct {
	OfferKey string
	SeenAt   string
}

// ===== seen =====
func (q *Queries) MarkSeen(ctx context.Context, arg MarkSeenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markSeen, arg.OfferKey, arg.SeenAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const nextPracticeQuestions = `-- name: NextPracticeQuestions :many
SELECT id, prep_id, category, question, difficulty, talking_points, confidence, practiced_count, created_at, updated_at
FROM interview_questions
WHERE prep_id = ?
ORDER BY confidence ASC, practiced_count ASC, id ASC
LIMIT ?
`

type NextPracticeQuestionsParams struct {
	PrepID int64
	Limit  int64
}

func (q *Queries) NextPracticeQuestions(ctx context.Context, arg NextPracticeQuestionsParams) ([]InterviewQuestion, error) {
	rows, err := q.db.QueryContext(ctx, nextPracticeQuestions, arg.PrepID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InterviewQuestion{}
	for rows.Next() {
		var i InterviewQuestion
		if err := rows.Scan(
			&i.ID,
			&i.PrepID,
			&i.Category,
			&i.Question,
			&i.Difficulty,
			&i.TalkingPoints,
			&i.Confidence,
			&i.PracticedCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const offerExists = `-- name: OfferExists :one
SELECT EXISTS(SELECT 1 FROM offers WHERE offer_key = ?)
`

func (q *Queries) OfferExists(ctx context.Context, offerKey string) (bool, error) {
	row := q.db.QueryRowContext(ctx, offerExists, offerKey)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const profileExists = `-- name: ProfileExists :one
SELECT EXISTS(SELECT 1 FROM profiles WHERE id = ?)
`

func (q *Queries) ProfileExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, profileExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const questionsForPrep = `-- name: QuestionsForPrep :many
SELECT id, prep_id, category, question, difficulty, talking_points, confidence, practiced_count, created_at, updated_at
FROM interview_questions
WHERE prep_id = ?
ORDER BY category, id
`

func (q *Queries) QuestionsForPrep(ctx context.Context, prepID int64) ([]InterviewQuestion, error) {
	rows, err := q.db.QueryContext(ctx, questionsForPrep, prepID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InterviewQuestion{}
	for rows.Next() {
		var i InterviewQuestion
		if err := rows.Scan(
			&i.ID,
			&i.PrepID,
			&i.Category,
			&i.Question,
			&i.Difficulty,
			&i.TalkingPoints,
			&i.Confidence,
			&i.PracticedCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTracked = `-- name: RemoveTracked :execrows
DELETE FROM tracker WHERE offer_key = ? AND profile_id = ?
`

type RemoveTrackedParams struct {
	OfferKey  string
	ProfileID int64
}

func (q *Queries) RemoveTracked(ctx context.Context, arg RemoveTrackedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeTracked, arg.OfferKey, arg.ProfileID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const removeWatch = `-- name: RemoveWatch :execrows
DELETE FROM watches WHERE name = ?
`

func (q *Queries) RemoveWatch(ctx context.Context, name string) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeWatch, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const salaryRows = `-- name: SalaryRows :many
SELECT salary_from, salary_to, currency, is_remote, experience_level, division
FROM offers
WHERE (CAST(?1 AS TEXT) IS NULL OR division = ?1)
  AND (CAST(?2 AS INTEGER) IS NULL OR is_remote = ?2)
  AND (CAST(?3 AS TEXT) IS NULL
       OR title LIKE ?3
       OR category LIKE ?3
       OR sub_category LIKE ?3
       OR skills LIKE ?3)
  AND (CAST(?4 AS TEXT) IS NULL OR locations LIKE ?4)
`

type SalaryRowsParams struct {
	Division sql.NullString
	Remote   sql.NullInt64
	Skill    sql.NullString
	City     sql.NullString
}

type SalaryRowsRow struct {
	SalaryFrom      sql.NullInt64
	SalaryTo        sql.NullInt64
	Currency        sql.NullString
	IsRemote        int64
	ExperienceLevel sql.NullString
	Division        string
}

func (q *Queries) SalaryRows(ctx context.Context, arg SalaryRowsParams) ([]SalaryRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, salaryRows,
		arg.Division,
		arg.Remote,
		arg.Skill,
		arg.City,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalaryRowsRow{}
	for rows.Next() {
		var i SalaryRowsRow
		if err := rows.Scan(
			&i.SalaryFrom,
			&i.SalaryTo,
			&i.Currency,
			&i.IsRemote,
			&i.ExperienceLevel,
			&i.Division,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedDefaultProfile = `-- name: SeedDefaultProfile :exec
INSERT INTO profiles (name, content, is_default, created_at, updated_at)
VALUES (?, '', 1, ?, ?)
`

type SeedDefaultProfileParams struct {
	Name      string
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) SeedDefaultProfile(ctx context.Context, arg SeedDefaultProfileParams) error {
	_, err := q.db.ExecContext(ctx, seedDefaultProfile, arg.Name, arg.CreatedAt, arg.UpdatedAt)
	return err
}

const seenKeys = `-- name: SeenKeys :many
SELECT offer_key FROM seen WHERE offer_key IN (/*SLICE:keys*/?)
`

func (q *Queries) SeenKeys(ctx context.Context, keys []string) ([]string, error) {
	query := seenKeys
	var queryParams []interface{}
	if len(keys) > 0 {
		for _, v := range keys {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:keys*/?", strings.Repeat(",?", len(keys))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:keys*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var offer_key string
		if err := rows.Scan(&offer_key); err != nil {
			return nil, err
		}
		items = append(items, offer_key)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDefaultProfile = `-- name: SetDefaultProfile :exec
UPDATE profiles SET is_default = (id = ?)
`

func (q *Queries) SetDefaultProfile(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, setDefaultProfile, id)
	return err
}

const setNotes = `-- name: SetNotes :execrows
UPDATE tracker SET notes = ?, updated_at = ?
WHERE offer_key = ? AND profile_id = ?
`

type SetNotesParams struct {
	Notes     string
	UpdatedAt string
	OfferKey  string
	ProfileID int64
}

func (q *Queries) SetNotes(ctx context.Context, arg SetNotesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setNotes,
		arg.Notes,
		arg.UpdatedAt,
		arg.OfferKey,
		arg.ProfileID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setProfileContent = `-- name: SetProfileContent :execrows
UPDATE profiles SET content = ?, updated_at = ? WHERE id = ?
`

type SetProfileContentParams struct {
	Content   string
	UpdatedAt string
	ID        int64
}

func (q *Queries) SetProfileContent(ctx context.Context, arg SetProfileContentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setProfileContent, arg.Content, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setStatus = `-- name: SetStatus :execrows
UPDATE tracker SET status = ?, updated_at = ?
WHERE offer_key = ? AND profile_id = ?
`

type SetStatusParams struct {
	Status    string
	UpdatedAt string
	OfferKey  string
	ProfileID int64
}

func (q *Queries) SetStatus(ctx context.Context, arg SetStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setStatus,
		arg.Status,
		arg.UpdatedAt,
		arg.OfferKey,
		arg.ProfileID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updatePrepReadiness = `-- name: UpdatePrepReadiness :execrows
UPDATE interview_preps SET readiness = ?, updated_at = ? WHERE id = ?
`

type UpdatePrepReadinessParams struct {
	Readiness int64
	UpdatedAt string
	ID        int64
}

func (q *Queries) UpdatePrepReadiness(ctx context.Context, arg UpdatePrepReadinessParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePrepReadiness, arg.Readiness, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateQuestionConfidence = `-- name: UpdateQuestionConfidence :execrows
UPDATE interview_questions
SET confidence = ?, practiced_count = practiced_count + 1, updated_at = ?
WHERE id = ?
`

type UpdateQuestionConfidenceParams struct {
	Confidence int64
	UpdatedAt  string
	ID         int64
}

func (q *Queries) UpdateQuestionConfidence(ctx context.Context, arg UpdateQuestionConfidenceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateQuestionConfidence, arg.Confidence, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertOffer = `-- name: UpsertOffer :exec


INSERT INTO offers (offer_key, title, company, division, category, sub_category,
    experience_level, salary_from, salary_to, currency, is_remote, is_hybrid,
    valid_from, valid_to, url, locations, skills, raw, fetched_at)
VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
ON CONFLICT(offer_key) DO UPDATE SET
    title=excluded.title, company=excluded.company, division=excluded.division,
    category=excluded.category, sub_category=excluded.sub_category,
    experience_level=excluded.experience_level, salary_from=excluded.salary_from,
    salary_to=excluded.salary_to, currency=excluded.currency,
    is_remote=excluded.is_remote, is_hybrid=excluded.is_hybrid,
    valid_from=excluded.valid_from, valid_to=excluded.valid_to,
    url=excluded.url, locations=excluded.locations, skills=excluded.skills,
    raw=excluded.raw, fetched_at=excluded.fetched_at
`

type UpsertOfferParams struct {
	OfferKey        string
	Title           string
	Company         string
	Division        string
	Category        sql.NullString
	SubCategory     sql.NullString
	ExperienceLevel sql.NullString
	SalaryFrom      sql.NullInt64
	SalaryTo        sql.NullInt64
	Currency        sql.NullString
	IsRemote        int64
	IsHybrid        int64
	ValidFrom       sql.NullString
	ValidTo         sql.NullString
	Url             sql.NullString
	Locations       sql.NullString
	Skills          sql.NullString
	Raw             string
	FetchedAt       string
}

// Queries for solid-jobs-skills, compiled by sqlc into internal/store/sqlcgen.
// The store package wraps these generated methods; no SQL is inlined in Go.
// ===== offers =====
func (q *Queries) UpsertOffer(ctx context.Context, arg UpsertOfferParams) error {
	_, err := q.db.ExecContext(ctx, upsertOffer,
		arg.OfferKey,
		arg.Title,
		arg.Company,
		arg.Division,
		arg.Category,
		arg.SubCategory,
		arg.ExperienceLevel,
		arg.SalaryFrom,
		arg.SalaryTo,
		arg.Currency,
		arg.IsRemote,
		arg.IsHybrid,
		arg.ValidFrom,
		arg.ValidTo,
		arg.Url,
		arg.Locations,
		arg.Skills,
		arg.Raw,
		arg.FetchedAt,
	)
	return err
}

const upsertWatch = `-- name: UpsertWatch :exec

INSERT INTO watches (name, division, params, created_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(name) DO UPDATE SET division = excluded.division, params = excluded.params
`

type UpsertWatchParams struct {
	Name      string
	Division  string
	Params    string
	CreatedAt string
}

// ===== watches =====
func (q *Queries) UpsertWatch(ctx context.Context, arg UpsertWatchParams) error {
	_, err := q.db.ExecContext(ctx, upsertWatch,
		arg.Name,
		arg.Division,
		arg.Params,
		arg.CreatedAt,
	)
	return err
}
